site_name: Estrutura Workshop 101

theme:
  name: material
  logo: assets/pao-de-queijo.png
  favicon: assets/pao-de-queijo.png
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - content.code.annotate
    - toc.integrate
    - toc.follow
    - navigation.path
    - navigation.top
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference

    # Note: Using the system theme works with the insiders version
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    # Palette toggle for automatic mode
    # - media: "(prefers-color-scheme)"
    #   primary: black
    #   accent: custom
    #   toggle:
    #     icon: material/brightness-auto
    #     name: Switch to light mode

repo_url: https://github.com/alecsandergr/estrutura-ws-101
repo_name: estrutura-ws-101
site_author: alecsandergr

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
  - pymdownx.snippets:
  - pymdownx.magiclink:
  - attr_list:
  - md_in_html:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - markdown.extensions.attr_list:
  - pymdownx.keys:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: index.md
  - Functions: functions.md
  - Steps: steps.md
# extra:
#   analytics:
#     provider: fathom